### ISSUE TITLE
If `title` contain `:` colon will parsing error

### ISSUE THREAD

**Issue by PH9** [ThaiProgrammer/tech-events-calendar#158] opened 2018-10-02 13:19 UTC

**Comment by chonla** [comment] 2018-10-04 07:02
This is expected behavior due to YAML specification. If you want to include ':' colon in your text, put single quote around the text.

**Comment by dtinth** [comment] 2018-10-04 08:17
As @chonla explained (thanks), to use colon we have to wrap with quotes.

Closing this one for now ;)

**Closed by dtinth** 2018-10-04 08:17 UTC
